// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $Accordion from "./islands/Accordion.tsx";
import * as $Menu from "./islands/Menu.tsx";
import * as $Share from "./islands/Share.tsx";
import * as $Tabs from "./islands/Tabs.tsx";
import * as $TabsWihContent from "./islands/TabsWihContent.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/Accordion.tsx": $Accordion,
    "./islands/Menu.tsx": $Menu,
    "./islands/Share.tsx": $Share,
    "./islands/Tabs.tsx": $Tabs,
    "./islands/TabsWihContent.tsx": $TabsWihContent,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
